#phyton.materials.density

from phyton.constants import *

class ρ:
    w = water = h2o = H2O = Quantity(1000, kg/(m**3), 'Density of Pure Water (H2O)')
    gasoline = Quantity(700, kg/(m**3), 'Density of Gasoline')
    Hg = mercury = Quantity(13600, kg/(m**3), 'Density of Mercury (Hg)')
    milk = Quantity(1030, kg/(m**3), 'Density of Milk')
    Mg = magnesium = Quantity(1700, kg/(m**3), 'Density of Magnesium (Mg)')
    Al = aluminium = Quantity(2691, kg/(m**3), 'Density of Aluminium (Al)')
    Cu = copper = Quantity(8960, kg/(m**3), 'Density of Copper (Cu)')
    Au = gold = Quantity(19300, kg/(m**3), 'Density of Gold (Au)')
    Fe = iron = Quantity(7800, kg/(m**3), 'Density of Iron (Fe)')
    Fe = iron = Quantity(7209, kg/(m**3), 'Density of Iron (Fe), cast')
    Pb = lead = Quantity(11342, kg/(m**3), 'Density of Lead (Pb)')
    Pt = platinum = Quantity(21400, kg/(m**3), 'Density of Platinum (Pt)')
    U = uranium = Quantity(18700, kg/(m**3), 'Density of Uranium (U)')
    Os = osmium = Quantity(22500, kg/(m**3), 'Density of Osmium (Os)')
    ice = Quantity(920, kg/(m**3), 'Density of Ice (H2O, solid state)')
    ice_0 = Quantity(2700, kg/(m**3), 'Density of Ice (H2O, solid state) at 0°C')
    air = Quantity(1.293, kg/(m**3), 'Density of Air')
    co2 = CO2 = carbon_dioxide = Quantity(1.977, kg/(m**3), 'Density of Carbon Dioxide Gas (CO2)')
    co = CO = carbon_monoxide = Quantity(1.25, kg/(m**3), 'Density of Carbon Monoxide Gas (CO)')
    H2 = h2 = hydrogen = Quantity(0.09, kg/(m**3), 'Density of Hydrogen Gas (H2)')
    He = he = helium = Quantity(0.178, kg/(m**3), 'Density of Helium Gas (He)')
    N2 = n2 = nitrogen = Quantity(1.251, kg/(m**3), 'Density of Nitrogen Gas (N2)')
    acetone = c3h6o = C3H6O = Quantity(785, kg/(m**3), 'Density of Acetone (C3H6O)')
    asphalt = Quantity(1506, kg/(m**3), 'Density of Asphalt')
    brass = Quantity(8394, kg/(m**3), 'Density of Brass')
    bronze = Quantity(8715, kg/(m**3), 'Density of Bronze')
    brick = Quantity(1794, kg/(m**3), 'Density of Common Brick')
    cement = Quantity(1506, kg/(m**3), 'Density of Cement (Portland)')
    chalk = Quantity(2195, kg/(m**3), 'Density of Chalk')
    plasticine = Quantity(3124, kg/(m**3), 'Density of Wet Plasticine')
    coal = Quantity(913, kg/(m**3), 'Density of Coal')
    coal_anthracite = Quantity(913, kg/(m**3), 'Density of Coal (anthracite)')
    coal_bituminous = Quantity(913, kg/(m**3), 'Density of Coal (bituminous)')
    coke = Quantity(1202, kg/(m**3), 'Density of Coke')
    corn = Quantity(593, kg/(m**3), 'Density of Corn (bulk)')
    glass = Quantity(3140, kg/(m**3), 'Density of Glass')
    gravel = Quantity(1922, kg/(m**3), 'Density of Gravel')
    coke = Quantity(1202, kg/(m**3), 'Density of Coke')
    kerosene = Quantity(817, kg/(m**3), 'Density of Kerosene')
    limestone = Quantity(2739, kg/(m**3), 'Density of Limestone')
    marble = Quantity(2.56, kg/(m**3), 'Density of Marble')
    paper = Quantity(929, kg/(m**3), 'Density of Paper')
    rubber = Quantity(1520, kg/(m**3), 'Density of Rubber')
    sand = Quantity(1602, kg/(m**3), 'Density of Sand')
    sandstone = Quantity(1442, kg/(m**3), 'Density of Sandstone')
    steel = Quantity(7769, kg/(m**3), 'Density of Steel')
    tin = Sn = Quantity(7337, kg/(m**3), 'Density of Tin (Sn)')
    zinc = Zn = Quantity(7049, kg/(m**3), 'Density of Zinc (Zn)')
